[package]
name = "api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "vidio-api"
path = "src/main.rs"

[dependencies]
tokio = { workspace = true }
tracing = { workspace = true }
time = { workspace = true }
axum = { workspace = true }
http-api = { workspace = true }
persistence = { workspace = true }
application = { workspace = true }
auth = { workspace = true }
addon-runtime = { workspace = true }
telemetry = { workspace = true }
